menu:
  首页: /
  存档: /archives
  关于: /about
  ToDo: /todolist
  

widgets:
- search
- category
- tagcloud
- weibo
- blogroll


excerpt_link: 阅读全文

plugins: 


twitter:
  username: moxie198
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: